server:
  port: 8082

spring:
  datasource:
    #DB_CLOSE_DELAY=-1 parameter appended to the end of the database URL.
    #When working with an in-memory database, we need to specify this, so the JPA implementation, which is Hibernate, won?t close the database while the application is running.
    #url: jdbc:hsqldb:mem:advisorDB;DB_CLOSE_DELAY=-1
    url: jdbc:hsqldb:file:D:/temp/advisorDB;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        jpa:
          compliance:
            proxy: false
        format_sql: true
        use_sql_comments: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

  sql:
    init:
      data-locations: classpath:db/init.sql, classpath:db/populateDb.sql
      mode: always
